## Notebook Outcomes

In this notebook we will learn:
<ul>
    <li>What is numpy and what is it good for</li> 
    <li>what are numpy arrays</li> 
    <li>functions on arrays</li> 
    <li>random number generation and stats</li> 
    <li>linear algebra</li>
</ul>

# `numpy`

`numpy` is another very popular package in the world of data science and machine learning. It is short for Numerical Python, and is one of the most important foundational packages for numerical computing in `python`.

Let's start off by importing the package.

In [5]:
# It is standard to import numpy as np

import numpy as np


### `numpy`'s ndarray

The `numpy` data object is know as an `ndarray` it is similar to a list

In [ ]:
# You can make an array with np.array
array1 = np.array([1,2,3,4])
print(array1)
print()
print(type(array1))

but it can have any finite number dimensions.

In [ ]:
array2 = np.array([[1,2],[2,1]])
print(array2)
print()
# np.shape() will give you the dimensions of the array
# array2 is a 2 by 2 array
print("array2 is a",np.shape(array2),"ndarray")

In [ ]:
array3 = np.array([[[1,2],[2,1]],[[2,3],[3,2]]])
print(array3)
print()
print("array3 is a",np.shape(array3),"ndarray")

We can keep going if we want to

In [ ]:
## Practice
## Make a 4 dimensional array and store it in array4

array4 = np.array(
[[[[1,2], [1,2]], [[1,2], [1,2]]], 
 [[[1,2], [1,2]], [[1,2], [1,2]]],
 [[[1,2], [1,2]], [[1,2], [1,2]]]
])
    
print(array4)
print("array4 is a",np.shape(array4),"ndarray")

#### Other Array Generators

As we've seen you can make arrays out of lists and lists of lists. There are also a number of built in array generators.

In [ ]:
# We can make an empty array
# np.empty(array_shape)
np.empty((2,2,2))

In [ ]:
# We can make an array of all ones
# np.ones(array_shape)
np.ones(12)

In [ ]:
#  An array of zeros
# np.zeros(array_shape)
np.zeros((4,4))

In [ ]:
# a 1d array for an interval
# np.linspace(start, end, number of entries)
np.linspace(0,1,10)

In [ ]:
# the numpy version of range allows 
# decimals
# np.arange(start,end,step_size)
np.arange(0,10,.1)

In [ ]:
# make a 2d grid
interval = np.linspace(-2,2,100)

# meshgrid takes in two intervals as arguments
# it outputs two arrays that give every x,y
# pair from the two intervals you enter
xs,ys = np.meshgrid(interval,interval)

# useful for calculations
z = xs ** 2 + ys**2

In [ ]:
# A sample plot using meshgrid
import matplotlib.pyplot as plt
plt.figure(figsize=(10,10))
plt.imshow(z,cmap=plt.cm.plasma)
plt.colorbar()
plt.title("Image of $x^2 + y^2$ for a grid of values")
plt.show()

In [ ]:
## Practice
## Using np.linspace make an interval from -1 to 3
## store it in x

x = np.linspace(-1, 3, 5)
print(x)



#### Indexing or Slicing an ndarray

Just like with lists, pandas DataFrames, or any other data structure you may want to access particular elements or subsets of an ndarray. Let's see how to do that below.

In [ ]:
# a is a random 50 by 2 array
# more on random arrays in a bit
a = 2*np.random.random((50,2)) - 1

In [ ]:
# I can get an individual entry like so
# the 1 row and 1 column entry
print(a[1,1])
print()
# the entire 4th row
print(a[4,:])
print()
# The entire 0th column
# note despite being a column it is output as a row vector
print(a[:,0])

In [ ]:
# You can get a slice of a as well
# the 1 through 4 rows
a[1:4,:]

In [ ]:
# You can index by logical conditions
# Every entry of a where a is positive
# Returned as a 1d array
a[a>0]

In [ ]:
# Only rows where the 0th columns is positive
# and the 1 column is negative
a[(a[:,0]>0) & (a[:,1] <0),:]

In [ ]:
## Practice
## Find all rows where the 1 column is greater than .25
## or 
## the 0 column is less than .25


b = a[(a[:, 1]>0.25)]
np.append(b, a[(a[:, 0]<0.25)], axis=0)
b


### Functions on ndarrays

ndarrays are nice because unlike base `python` lists and arrays `numpy` has been designed to allow very fast elementwise operations.

In [ ]:
## Practice
## What happens here
[1,2] + [2,3]

In [ ]:
## What about here?
np.array([1,2]) + np.array([2,3])

In [ ]:
## What happens here
2 * [3,4]

In [ ]:
## What about here?
2*np.array([3,4])

In [ ]:
# Okay how about
y = 3*[1,2,3] + 2

In [ ]:
# and this?
y = 3*np.array([1,2,3]) + 2

In [ ]:
# There are even a number of popular
# built in math functions for ndarray
# absolute value
# This is the x from your earlier practice block
np.abs(x)

In [ ]:
# square root
np.sqrt(np.abs(x))

In [ ]:
# the floor function
np.floor(x)

In [ ]:
## Practice
## using np.exp define y to be 
## e^(x+3) + log(|x|+1)

y = np.exp(np.array(x)+3)+np.log





### Pseudorandom ndarrays and Stat Functions

`numpy` is useful for generating random numbers as well. We can look at common statistics of arrays too.

In [ ]:
# random generators are stored in np.random
# a np.random.random() gives a uniform random number in [0,1]
np.random.random()

In [ ]:
# np.random.randn() is a normal(0,1) number
# a single draw
print(np.random.randn())
print()

# an array of draws
np.random.randn(10,2)

In [ ]:
# np.random.binomial()
# an array of binomial(n,p) outcomes
np.random.binomial(n=4,p=.3,size=(10,10))

In [ ]:
## Practice
# make a 20 by 3 array of random normal draws
# call it X
X = np.random.randn(20,3)






In [ ]:
# We can use np.mean to get the overall
# array mean
print(np.mean(X))
print()

# or the row mean
print(np.mean(X,axis=0))
print()

# or the column mean
# again output as a row vector
print(np.mean(X,axis=1))

Other common functions are `np.std()` for standard deviation, `np.sum()` for sum, `np.var()` for variance, `np.min()` for min, `np.max()` for max, `np.argmin()` for where the min occurs, `np.argmax()` for where the max occurs.

In [ ]:
## Practice
## where does the max value occur in each column of X?






In [ ]:
# Another useful function is np.cumsum()
x = np.random.random(10)

np.cumsum(x)

# What do you think it does?

### Linear Algebra with `numpy`

A final important use for us is `numpy` as a way to perform linear algebra calculations.

In [6]:
# We can think of a 2D array as a matrix
A = np.random.binomial(n=4,p=.3,size=(2,2))

A

array([[1, 1],
       [0, 0]])

In [7]:
# A 1d array can be a row vector
x = np.array([1,2])
x

array([1, 2])

In [8]:
# or a column vector
x.reshape(-1,1)

array([[1],
       [2]])

In [9]:
# We can now calculate A*x
# matrix.dot() is used for matrix mult
A.dot(x.reshape(-1,1))

array([[3],
       [0]])

In [10]:
## Practice
# Take the matrix B and multiply it with a column
# vector of 1s
B = np.random.binomial(n=5,p=.6,size=(3,3))







In [11]:
# numpy.linalg contains a number of useful
# matrix operations
from numpy.linalg import inv, eig, det

In [12]:
# the inverse of A
inv(A)

LinAlgError: Singular matrix

In [13]:
# the det of A
det(A)

0.0

In [14]:
# the eigenvalues and eigenvectors of A
eig(A)

(array([1., 0.]),
 array([[ 1.        , -0.70710678],
        [ 0.        ,  0.70710678]]))

In [15]:
# matrix.transpose() computes the transpose of the matrix
A.transpose()

array([[1, 0],
       [1, 0]])

In [16]:
## Practice
b = np.array([2,5]).reshape(-1,1)

## Solve Ax = b for x



That's it!

You should now try to see if you can solve the numpy - Skill Check notebook.

In [17]:
A = [1, 2, 3, 4]
B = [2, 3, 4, 5]

A*4

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [34]:
A = np.array([1, 2, 3, 4])

B = np.array([2, 3, 4, 5])


In [35]:
A+B

array([3, 5, 7, 9])

In [36]:
A*B

array([ 2,  6, 12, 20])

In [37]:
C = np.array([[0, 0, 0,], 
              [0.25, 0.50, 0.25], 
              [0.1, 0.2, 0.3]])
C

array([[0.  , 0.  , 0.  ],
       [0.25, 0.5 , 0.25],
       [0.1 , 0.2 , 0.3 ]])

In [28]:
4*C

array([[0. , 0. , 0. ],
       [1. , 2. , 1. ],
       [0.4, 0.8, 1.2]])

In [29]:
np.matmul(A, B)

40

In [30]:
D = np.array([[1, 2, 3], 
            [4, 5, 6],
            [7, 8, 9]])

In [31]:
C*D

array([[0. , 0. , 0. ],
       [1. , 2.5, 1.5],
       [0.7, 1.6, 2.7]])

In [32]:
np.matmul(C, D)

array([[0. , 0. , 0. ],
       [4. , 5. , 6. ],
       [3. , 3.6, 4.2]])

In [33]:
np.dot(C, D)

array([[0. , 0. , 0. ],
       [4. , 5. , 6. ],
       [3. , 3.6, 4.2]])